spring.application.name=statstracker
spring.datasource.url=jdbc:postgresql://localhost:5432/statstracker
spring.datasource.username=postgres
spring.datasource.password=PGVY45CG8T6A
spring.jpa.hibernate.ddl-auto=update